version: '2.1'

services:
  rancher:
    image: rancher/rancher:${APP_VERSION}
    restart: unless-stopped
    container_name: ${APP_NAME}
    user: root
    volumes:
      - ${VOLUMES_BASE}/${APP_NAME}/mysql:/var/lib/mysql
    ports:
      - "8899:80"
      - "8889:443"
      