version: '2.1'

services:
  hitchhiker:
    image: jboss/keycloak:${APP_VERSION}
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mac.k.9kb.me
      - DB_PORT=3306
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=Keycloak@123
      - KEYCLOAK_LOGLEVEL=INFO   # 支持的日志级别ALL，DEBUG，ERROR，FATAL，INFO，OFF，TRACE和WARN。
    ports:
      - "18855:8080"
